version: '3.7'                                                                       
services:                                                                           
    web:                                                                            
        ports:                                                                      
            - 9971:80
