version: "3.7"                                                                      
services:                                                                           
    web:                                                                            
        image: meta-building-ltd-website
